services:
  api:
    image: ghcr.io/steven230500/introduce-api:latest
    restart: unless-stopped
    environment:
      PORT: 8080
      UPLOADS_DIR: /uploads
      FILES_BASE_URL: ${FILES_BASE_URL}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
    volumes:
      - uploads:/uploads
    networks:
      - infra_network

volumes:
  uploads:

networks:
  infra_network:
    external: true
