-- What went up on the screen, and when.
--
-- Two questions a church asks after the fact, and neither had an answer: what
-- did we sing last Sunday, and which songs did we project this quarter for the
-- licence report. Both are the same record read two ways.
--
-- One row per stretch of time an item was on air, not per slide: a licence
-- report counts a song once each time it is used, and a service history reads
-- as a running order, not as two hundred page turns.
--
-- The song's title, author and licence number are copied in rather than joined.
-- A report for last year must still say what was projected last year after the
-- song has been renamed, corrected or deleted from the library.
create table if not exists projection_log (
    -- Generated by the app, not here. The app records while offline and sends
    -- later, possibly twice; a client id is what makes the second send a no-op.
    id              uuid        primary key,
    org_id          uuid        not null references organizations (id) on delete cascade,
    recorded_by     uuid        references users (id) on delete set null,

    collection_id   uuid,
    collection_name text        not null default '',
    item_type       text        not null,
    title           text        not null default '',

    song_id         uuid,
    song_author     text,
    song_copyright  text,
    ccli_number     text,

    started_at      timestamptz not null,
    ended_at        timestamptz not null,

    constraint projection_log_ordered check (ended_at >= started_at)
);

-- Every read is "this church, this stretch of dates".
create index if not exists projection_log_org_time_idx
    on projection_log (org_id, started_at desc);
